

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	username VARCHAR(50),
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(200)
)


CREATE TABLE budget_periods (
	id SERIAL PRIMARY KEY,
	period_type VARCHAR(100),
	start_date TIMESTAMP WITH TIME ZONE NOT NULL,
	end_date TIMESTAMP WITH TIME ZONE NOT NULL,
	income INTEGER DEFAULT 0,
	savings INTEGER DEFAULT 0 CHECK(savings >= 0 AND savings <= 100),
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE fixed_expenses (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	amount INTEGER NOT NULL,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	budget_period_id INTEGER NOT NULL REFERENCES budget_periods(id) ON DELETE CASCADE
);



CREATE TABLE transactions (
	id SERIAL PRIMARY KEY,
	transaction_type VARCHAR(100) NOT NULL, 
	note VARCHAR(300) DEFAULT '',
	date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	category VARCHAR(200) NOT NULL,
	amount INTEGER NOT NULL CHECK(amount >= 0), 
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	budget_period_id INTEGER NOT NULL REFERENCES budget_periods(id) ON DELETE CASCADE
);