version: "3.9"

services:
  api:
    container_name: piggibank-backend
    image: piggibank-backend
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
